name: Build & Test

on:
  # pull_request:
  #  branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn run bootstrap:install

      - name: Build
        run: yarn run package:build

      - name: Test
        run: yarn run package:test:unit
