name: Release deploy

on:
  release:
    types:
      - created
    tags:
      - '[a-z]@[0-9]+.[0-9]+.[0-9]+**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Build packages & docs
        run: |
          yarn run package:deploy:ready
          yarn run package:build
          yarn run docs:build

      - name: Test packages
        run: yarn run package:test

  # Github page
  # document-pub:
  #   runs-on: ubuntu-latest
  #   needs: release
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 18
  #         registry-url: https://registry.npmjs.org/

  #     - name: Build document
  #       run: |
  #         yarn run package:deploy:ready
  #         yarn run docs:build

  #     - name: Github pages publish
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: './document/docs/.vitepress/dist'

  # NPM 패키지 퍼블리시
  npm-publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Build packages
        run: |
          yarn run package:deploy:ready
          yarn run package:build

      - name: NPM publish array
        if: ${{ always() && startsWith(github.ref, 'refs/tags/array') }}
        run: npm publish ./packages/helpdesk-array
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: NPM publish color
        if: ${{ always() && startsWith(github.ref, 'refs/tags/color') }}
        run: npm publish ./packages/helpdesk-color
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: NPM publish core
        if: ${{ always() && startsWith(github.ref, 'refs/tags/core') }}
        run: npm publish ./packages/helpdesk-core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: NPM publish date
        if: ${{ always() && startsWith(github.ref, 'refs/tags/date') }}
        run: npm publish ./packages/helpdesk-date
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: NPM publish functional
        if: ${{ always() && startsWith(github.ref, 'refs/tags/functional') }}
        run: npm publish ./packages/helpdesk-functional
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: NPM publish module
        if: ${{ always() && startsWith(github.ref, 'refs/tags/module') }}
        run: npm publish ./packages/helpdesk-module
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: NPM publish number
        if: ${{ always() && startsWith(github.ref, 'refs/tags/number') }}
        run: npm publish ./packages/helpdesk-number
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: NPM publish point
        if: ${{ always() && startsWith(github.ref, 'refs/tags/point') }}
        run: npm publish ./packages/helpdesk-point
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: NPM publish string
        if: ${{ always() && startsWith(github.ref, 'refs/tags/string') }}
        run: npm publish ./packages/helpdesk-string
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: NPM publish types
        if: ${{ always() && startsWith(github.ref, 'refs/tags/types') }}
        run: npm publish ./packages/helpdesk-types
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

