name: Release deploy

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Build packages & docs
        run: |
          yarn run package:deploy:ready
          yarn run package:build
          yarn run docs:build

      - name: Test packages
        run: yarn run package:unit

  # Github page
  document-pub:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Build document
        run: |
          yarn run package:deploy:ready
          yarn run docs:build

      - name: Github pages publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './document/docs/.vitepress/dist'

  # NPM 패키지 퍼블리시
  npm-publish:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Build packages
        run: |
          yarn run package:deploy:ready
          yarn run package:build

      - name: NPM publish
        run: |
          npm publish ./packages/helpdesk-array
          npm publish ./packages/helpdesk-core
          npm publish ./packages/helpdesk-date
          npm publish ./packages/helpdesk-functional
          npm publish ./packages/helpdesk-number
          npm publish ./packages/helpdesk-point
          npm publish ./packages/helpdesk-storage
          npm publish ./packages/helpdesk-string
          npm publish ./packages/helpdesk-timer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
